name = "cloudflare-workers-discord-bot"
type = "webpack"
account_id = "5a883b414d4090a1442b20361f3c43a9"
workers_dev = true
webpack_config = "webpack.config.js"

vars = { PUBLIC_KEY = "1b780f7f71ac39645d44cc4dce8fa78c860d0157cb0912d755b7a7cb95394532", APPLICATION_ID = "799627301675466772", ALGOLIA_APP_ID = "BH4D9OD16A", ALGOLIA_API_KEY = "b23088ab4d346409f9d3ece6606344c3", ALGOLIA_INDEX_NAME = "developers-cloudflare" }

kv_namespaces = [
	 { binding = "KV", id = "6d01bc2fde944702aed90de4f4ef5ae8" }
]

[triggers]
crons = ["*/15 * * * *"]